# GitHub Accion File to run a python script
name: My Action
on:
    # Trigger the workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    Run-Python-Script:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Save output
              uses: actions/upload-artifact@v4
              with:
                  name: output
                  path: ./data

            - name: Run Python Script
              run: python main.py