name: My Action
on:
    workflow_dispatch:
jobs:
    Run-Python-Script:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Set GITHUB_WORKSPACE variable
              run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV

            - name: Run Python Script
              run: python main.py

            - name: Save output
              uses: actions/upload-artifact@v4
              with:
                  name: output.csv
                  path: ./data